[#119] - Preloading the template chunk for the certificate file
OpenCerts/opencerts-website pull request #121
Opened 2019-03-14 08:00 UTC by sumitnitsurat

- added the preloading of templates before the verification starts.

2019-03-21 07:48 UTC, rjchow commented
@sumitnitsurat please review and write tests when you get back 😜

2019-03-27 02:47 UTC, rjchow requested changes

2019-03-27 02:47 UTC, rjchow commented on src/sagas/templates.test.js
> +import json from "../../tests_fixture/NP_Certs_FT_BMS.json";
i think just use a minimal cert inline instead of using a full cert

2019-03-28 03:08 UTC, sumitnitsurat commented on src/sagas/templates.test.js
> +import json from "../../tests_fixture/NP_Certs_FT_BMS.json";
We have any function which returns the minimal cert or you want me to remove the data from this cert itself ?

2019-03-28 11:39 UTC, rjchow commented on src/sagas/templates.test.js
> +import json from "../../tests_fixture/NP_Certs_FT_BMS.json";
you can use this: https://github.com/OpenCerts/opencerts-website/blob/master/src/sagas/testutils.js

2019-04-05 07:20 UTC, rjchow approved these changes

2019-04-05 07:30 UTC, merged