Fix/try another link
OpenCerts/opencerts-website pull request #141
Opened 2019-04-02 02:39 UTC by sumitnitsurat

- Resetting the certificate state to initial state.

2019-04-16 08:45 UTC, yehjxraymond commented on src/reducers/certificate.js
> +  RESET_CERTIFICATE: "RESET_CERTIFICATE",
Possible to use `UPDATE_CERTIFICATE` action with empty certificate instead? That way, no need for new action.

2019-04-18 05:50 UTC, sumitnitsurat commented on src/reducers/certificate.js
> +  RESET_CERTIFICATE: "RESET_CERTIFICATE",
Can not use "UPDATE_CERTIFICATE" directly as it calls verify certificate calls subsequently.

2019-04-29 03:32 UTC, rjchow requested changes
add test

2019-05-02 08:38 UTC, rjchow commented on src/reducers/certificate.test.js
> +      const action = {
should use this instead
https://github.com/OpenCerts/opencerts-website/blob/e369fe2309bc03e4b4bdef083e3eed3a44aaa060/src/reducers/certificate.js#L303

2019-05-02 08:53 UTC, sumitnitsurat commented on src/reducers/certificate.test.js
> +      const action = {
added test for action also.

2019-05-02 09:03 UTC, rjchow commented on src/reducers/certificate.test.js
> +      const action = {
no need, just use the exported function directly instead of replicating the action generator here

2019-05-03 07:56 UTC, rjchow approved these changes

2019-05-03 08:21 UTC, merged