Feat/dns verification
OpenCerts/opencerts-website pull request #362
Opened 2019-07-12 07:48 UTC by sumitnitsurat

- DNS verification added for document store
- Added unit test for dns verification 
- Create New issue for tls library used in dnsprove

2019-07-15 05:12 UTC, rjchow commented on package.json
> +    "tls": "0.0.1",
what's this library used for?

2019-07-18 02:29 UTC, yehjxraymond commented on package.json
> +    "opencerts-dnsprove": "^2.0.0",
Needs to be in @govtechsg org.

2019-07-18 02:29 UTC, yehjxraymond commented on package.json
> +    "tls": "0.0.1",
If it's suppose to be in dnsprove, shoudl move there instead.

2019-07-19 07:25 UTC, Nebulis commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.js
> +      if (next.registry && !prev.isRegistry) prev.isRegistry = true;
minor comment but the condition `!prev.isRegistry` is not necessary

2019-07-19 07:26 UTC, Nebulis commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.js
> +  test("when multiple registry is verified", () => {
let's differentiate the test case in their description

2019-07-19 07:34 UTC, Nebulis commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.js
> +  });
What about those use cases:
- testValue = []
- testValue = [{ registry: "demo", dns: "demo.com" }, { registry: false, dns: "abc.com" }]
- testValue = [{ registry: false, dns: "abc.com" }, { registry: "demo", dns: "demo.com" }]

2019-07-20 07:18 UTC, Nebulis commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.js
> +  });
and so ?it's still possible to call that function that way

2019-07-20 07:18 UTC, Nebulis commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.js
> +  test("when multiple registry is verified", () => {
test description must reflect what the test is ding, there are the same description twice

2019-07-20 07:21 UTC, Nebulis commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.js
> +      if (next.registry && !prev.isRegistry) prev.isRegistry = true;
up to the opener to resolve discussion :)

2019-07-20 07:29 UTC, sumitnitsurat commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.js
> +  test("when multiple registry is verified", () => {
something like this "should return appropriate display text when multiple registry is verified"

2019-07-20 07:30 UTC, sumitnitsurat commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.js
> +      if (next.registry && !prev.isRegistry) prev.isRegistry = true;
okay :p

2019-07-20 07:34 UTC, sumitnitsurat commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.js
> +  });
when there is no registry and dns saga test will fail. this component code will never execute.

2019-07-22 04:37 UTC, Nebulis commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.js
> +  test("when multiple registry is verified", () => {
yup this sounds better

2019-07-22 05:29 UTC, Nebulis commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.js
> +      if (next.registry && !prev.isRegistry) prev.isRegistry = true;
What's the issue on setting isRegistry again and again ?

Anyway I actually have another suggestion to change the function:

```
if(some(identityStatus, (idontknowhowtonamethis) => idontknowhowtonamethis.isRegistry)) {
  return "Accredited by SSG";
} else {
// note filter Boolean is to remove empty values
  return `Issued by ${identityStatus.map((idontknowhowtonamethis) =>idontknowhowtonamethis.dns).filter(Boolean).dns.join(" & ")}`
}
```

the issue with the current function is that there is `no comments/explanation` and the intent using a reducer is not really clear as it's doing 2 things at the same time

2019-07-22 07:08 UTC, rjchow requested changes
the verification logic looks correct but the flow is hard to follow - we'll need to refactor this in the following days.

aside from that there's also the rendering issue which i posted a screenshot of on telegram

do add in the integration test cases below as well for the various combinations

### Single Issuer
##### Valid (Green)
######Schema 1.5:
Accredited Issuer

###### Schema 2.0
Accredited Issuer
DNS Issuer

##### Invalid (means it should show red and not progress)
###### Schema 1.5
Issuer not on registry
###### Schema 2.0
No identityProof, issuer not on registry
Has identityProof, DNS records has wrong address
Has identityProof, no OpenAtts records

### Multiple Issuer
##### Valid
All accredited issuers: should show accredited cert
All DNS issuers: should show issued by DNS names
Mix of accredited issuers & DNS issuers: should show accredited cert

##### Invalid (show red and not render cert)
Mix of valid and invalid issuers
All invalid issuers

2019-07-22 11:49 UTC, sumitnitsurat commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.js
> +      if (next.registry && !prev.isRegistry) prev.isRegistry = true;
We are already iterating on the same array twice in our code ..with this method in case of dns it will iterate 4 times on the same array to return us the required value..

2019-07-22 11:49 UTC, sumitnitsurat commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.js
> +  test("when multiple registry is verified", () => {
updated please check .

2019-07-22 12:00 UTC, Nebulis commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.js
> +      if (next.registry && !prev.isRegistry) prev.isRegistry = true;
What's the issue with that ? performance concern to iterate over tiny array ?

readabiliy > performance unless performance is an actual issue. On top of that this function iterate only twice in that case

2019-07-24 01:45 UTC, sumitnitsurat commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.js
> +      if (next.registry && !prev.isRegistry) prev.isRegistry = true;
ok

2019-07-24 07:40 UTC, sumitnitsurat commented on src/sagas/certificate.js
> +  trace(`DNS records: ${dnsRecords}`); // dnsRecords: [{addr: "0xabc", netId: 3}]
fixed it.

2019-07-24 07:41 UTC, sumitnitsurat commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.test.js
> +  });
Should I resolve this ?

2019-07-24 07:41 UTC, sumitnitsurat commented on src/components/CertificateVerifyBlock/CertificateVerifyBlock.js
> +      if (next.registry && !prev.isRegistry) prev.isRegistry = true;
fixed it ..please check

2019-07-24 07:42 UTC, sumitnitsurat commented on src/sagas/certificate.test.js
> +        documentSotre: ethereumAddress
fixed it.

2019-07-24 07:43 UTC, sumitnitsurat commented
> the verification logic looks correct but the flow is hard to follow - we'll need to refactor this in the following days.
> 
> aside from that there's also the rendering issue which i posted a screenshot of on telegram
> 
> do add in the integration test cases below as well for the various combinations
> 
> ### Single Issuer
> ##### Valid (Green)
> ######Schema 1.5:
> Accredited Issuer
> 
> ###### Schema 2.0
> Accredited Issuer
> DNS Issuer
> 
> ##### Invalid (means it should show red and not progress)
> ###### Schema 1.5
> Issuer not on registry
> 
> ###### Schema 2.0
> No identityProof, issuer not on registry
> Has identityProof, DNS records has wrong address
> Has identityProof, no OpenAtts records
> 
> ### Multiple Issuer
> ##### Valid
> All accredited issuers: should show accredited cert
> All DNS issuers: should show issued by DNS names
> Mix of accredited issuers & DNS issuers: should show accredited cert
> 
> ##### Invalid (show red and not render cert)
> Mix of valid and invalid issuers
> All invalid issuers

I will create a new issue for that to refactor and add integration test for this.

2019-07-24 07:59 UTC, rjchow commented
do the tests in this merge so that we can have confidence that the verification logic works - right now we don't run any tests to check that cert verification is correct so that's very dangerous

2019-07-25 09:00 UTC, rjchow reviewed
left two comments the rest are correct

2019-07-26 04:00 UTC, rjchow approved these changes

2019-07-26 04:49 UTC, merged