fix: prevent exhausting failover providers on erc165 reverts
OpenCerts/opencerts-website pull request #806
Opened 2024-10-29 18:39 UTC by eli-lim

### Background

1. I noticed slowness when checking my degree on the site - took about 4 - 5s to verify
2. Looking at the networks tab, I noticed it was making a bunch of requests to different public node providers in sequence

https://github.com/user-attachments/assets/dae59424-1c60-45c7-a594-743ffe0c8527

### Root cause
1. [oa-verify](https://github.com/Open-Attestation/oa-verify/blob/0492679f4f24df164d93e699a5845b30d39ab14d/src/common/utils.ts#L240) is checking if the documentStore supports some interface, compliant with the ERC165 spec.
2. When the rpc call returns `execution reverted`, ethers will throw an error 
4. Website's `OAFailoverProvider` catches this and moves on to the next provider, until the list of providers is exhausted

### Fix
1. (This PR) Stop the `OAFailoverProvider` from overzealously retrying on `erc165` reverts
2. (Optionally) switch to use [public node providers with lower latency](https://chainlist.org/?search=ethereum)
    > Ignoring other concerns like privacy / agreements with the existing node providers

Doing these:

https://github.com/user-attachments/assets/34217fd1-f390-4c93-b3f3-d63db6775d6c

2024-11-19 09:16 UTC, HJunyuan requested changes
@eli-lim Thank you for proposing these improvements!

I've made a few minor suggestions before we proceed to merge this PR in.

2024-11-19 09:16 UTC, HJunyuan commented on src/services/failover-provider.ts
> +      ethersError.code === "CALL_EXCEPTION"
Propose regex check instead for cases where `params.transaction.data` is undefined:

```typescript
(undefined).startsWith("0x01ffc9a7") // ❌ TypeError is thrown instead which may impede actual Ethers error from being thrown
/^0x01ffc9a7.*$/.test(undefined)     // ✅ false
```

```suggestion
    // Avoid retries if the function selector inside calldata is "supportsInterface(bytes4)"
    // See https://eips.ethereum.org/EIPS/eip-165
    // isBatchableDocumentStore: https://github.com/Open-Attestation/oa-verify/blob/0492679f4f24df164d93e699a5845b30d39ab14d/src/common/utils.ts#L237-L244
    // Keccak256("supportsInterface(bytes4)") = 0x01ffc9a7
    const erc165SupportsInterfaceRegex = /^0x01ffc9a7.*$/
    return (
      method === "call" &&
      erc165SupportsInterfaceRegex.test(params?.transaction?.data) &&
      ethersError?.code === "CALL_EXCEPTION"
```

2024-11-19 09:16 UTC, HJunyuan commented on src/services/failover-provider.ts
> +          return false;
```suggestion
          throw error;
```

2024-11-22 12:36 UTC, eli-lim commented on src/services/failover-provider.ts
> +      ethersError.code === "CALL_EXCEPTION"
I've made this more generic. It shouldn't retry on any call exception, not just those originating from ERC165 reverts

2024-12-12 06:55 UTC, HJunyuan commented
@eli-lim My apologies, we would still need to perform `isErc165Check()` because the Ethers library also throws a `CALL_EXCEPTION` for other failures (e.g. when Infura is unreachable)

![CALL_EXCEPTION](https://github.com/user-attachments/assets/40dd49d3-9de0-4984-a376-aef9e80160de)

To avoid any further inconvenience to you, we can also take over from here to implement the changes in a separate PR.

2024-12-15 01:57 UTC, closed without merging